name: "CI"

on:
  workflow_call:
    inputs:
      jdk:
        required: false
        type: string
        default: '17'
      script:
        required: true
        type: string
        description: "Script to execute"
      args:
        required: false
        type: string
        default: ''
        description: "Arguments for the script"

# Cancel any previous runs on the same PR
#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true

jobs:
  run-worker:
    needs: setup
    uses: ./.github/workflows/worker.yml
    with:
      script: ${{ inputs.script }}
      args: ${{ inputs.args }}
      java-version: ${{ inputs.jdk }}
