name: "CI"

on:
  workflow_call:
    inputs:
      script:
        required: true
        type: string
        description: "Script to execute"
      args:
        required: false
        type: string
        default: ''
        description: "Arguments for the script"

# Cancel any previous runs on the same PR
#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'  # Fixed to JDK 17

  run-worker:
    needs: setup
    uses: ./.github/workflows/worker.yml
    with:
      script: ${{ inputs.script }}
      args: ${{ inputs.args }}
