name: "CI"

on:
  workflow_call:
    inputs:
      jdk:
        required: false
        type: string
        default: '17'

# Cancel any previous runs on the same PR
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  run-unit-tests:
    name: "unit tests"
    strategy:
      fail-fast: false
      matrix:
#        Dtest: [ "V*", "W*" ]
        Dtest: [ "A*,B*", "C*", "D*,E*,F*", "G*,H*", "I*,J*", "K*,L*", "M*,N*", "O*,P*", "Q*", "R*", "S*", "T*,U*", "V*,W*,X*,Y*,Z*", "nonexistingtest" ]
    uses: ./.github/workflows/worker.yml
    with:
      script: ".github/scripts/run-maven-command.sh test -pl '!integration-tests,!:druid-it-tools,!:druid-it-image,!:druid-it-cases' -Dtest='${{ matrix.Dtest }}' -Dsurefire.failIfNoSpecifiedTests=false -P skip-static-checks -Dweb.console.skip=true -Dmaven.javadoc.skip=true -Dmaven.test.failure.ignore=true -Djacoco.skip=true"
      jdk: ${{ inputs.jdk }}
      artifact_prefix: "unit-test-reports"
      key: ${{ matrix.Dtest }}

  reporting:
    name: "report-unit-test-failures"
    needs: run-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Download reports for all unit test jobs
        uses: actions/download-artifact@v4
        with:
          pattern: "unit-test-reports-*"
          path: target/surefire-reports

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
