name: "CI"

on:
  workflow_call:
    inputs:
      jdk:
        required: false
        type: string
        default: '17'

# Cancel any previous runs on the same PR
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  run-unit-tests:
    name: "unit tests"
    strategy:
      fail-fast: false
      matrix:
        dtest: [ "A*,B*", "C*,D*" ]
    uses: ./.github/workflows/worker.yml
    with:
      script: ".github/scripts/run-tests.sh"
      args: "--dtest '${{ matrix.dtest }}'"
      jdk: ${{ inputs.jdk }}
