name: Check PR Approval

on:
  pull_request:
    types:
      - synchronize
      - opened
  pull_request_review:
    types:
      - submitted

jobs:
  check-approval:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Debugging: Print the value of review state
      - name: Print Review State
        run: |
          echo "Review state: ${{ github.event.review.state }}"

      - name: Conditional Echo
        if: github.event.review.state == 'approved'
        run: |
          echo "The PR is approved!"
