name: "Worker"

on:
  workflow_call:
    inputs:
      jdk:
        required: false
        type: string
        default: '17'
      script:
        required: true
        type: string
        description: "Script to execute"
      key:
        required: false
        type: string
        description: "Key for the matrix"
      artifact_prefix:
        required: false
        type: string
        description: "Prefix for the artifact name"
      artifacts_to_download:
        required: false
        type: string
        description: "Artifacts to download. For example: 'unit-test-reports-*'"

env:
  FORCE_COLOR: 2

jobs:
  execute:
    name: "Execute (${{ inputs.key }})"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ inputs.jdk }}

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16.17.0

      - name: Download required artifacts
        if: ${{ inputs.artifacts_to_download != '' }}
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ inputs.artifacts_to_download }}
          merge-multiple: true

      - name: 'Execute script: (${{ inputs.key }})'
        run: |
          ./${{ inputs.script }} 

      - name: Calculate hash for artifact name
        run: |
          ./.github/scripts/make-hash-for-artifact-name.sh "${{ inputs.key }}"

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: "${{ inputs.artifact_prefix }}-${{ env.HASH }}"
          path: |
           ./**/TEST-*.xml
           ./**/target/jacoco*.exec
