name: "Worker"

on:
  workflow_call:
    inputs:
      jdk:
        required: false
        type: string
        default: '17'
      script:
        required: true
        type: string
        description: "Script to execute"
      args:
        required: false
        type: string
        description: "Arguments for the script"
      upload_surefire_reports:
        required: false
        type: boolean
        description: "Upload surefire reports"

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ inputs.jdk }}

      - name: Execute script
        run: |
          ./${{ inputs.script }} ${{ inputs.args }} 

      - name: Collect surefire reports
        if: ${{ always() && inputs.upload_surefire_reports }}
        run: |
          mkdir -p target/surefire-reports
          find . -type f -name "TEST-*.xml" -exec cp {} target/surefire-reports \;

      - name: Calculate hash for input args
        if: ${{ always() && inputs.upload_surefire_reports }}
        shell: bash
        run: |
          HASH=$(echo -n "${{ inputs.args }}" | sha256sum | cut -d' ' -f1 | cut -c1-8)
          echo "HASH=$HASH" >> $GITHUB_ENV

      - name: Upload surefire reports
        if: ${{ always() && inputs.upload_surefire_reports }}
        uses: actions/upload-artifact@v4
        with:
          name: "surefire-reports-${{ env.HASH }}-${{ github.run_attempt }}"
          path: target/surefire-reports
