name: "Worker"

on:
  workflow_call:
    inputs:
      jdk:
        required: false
        type: string
        default: '17'
      script:
        required: true
        type: string
        description: "Script to execute"
      key:
        required: false
        type: string
        description: "Key for the matrix"
      artifact_prefix:
        required: false
        type: string
        description: "Prefix for the artifact name"

jobs:
  execute:
    name: "Execute (${{ inputs.key }})"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ inputs.jdk }}

      - name: 'Execute script: (${{ inputs.key }})'
        run: |
          ./${{ inputs.script }} 

      - name: Calculate hash for artifact name
        run: |
          ./.github/scripts/make-hash-for-artifact-name.sh "${{ inputs.key }}"

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: "${{ inputs.artifact_prefix }}-${{ env.HASH }}"
          path: |
           ./**/TEST-*.xml
           ./**/target/jacoco*.exec
