name: "Worker"

on:
  workflow_call:
    inputs:
      jdk:
        required: false
        type: string
        default: '17'
      script:
        required: true
        type: string
        description: "Script to execute"
      args:
        required: false
        type: string
        description: "Arguments for the script"
      upload_reports:
        required: false
        type: boolean
        description: "Upload report artifacts"
      artifact_prefix:
        required: false
        type: string
        description: "Prefix for the artifact name"
      report_directory_pattern:
        required: false
        type: string
        description: "Pattern to match report files (e.g., './**/surefire-reports/**/*.xml')"

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ inputs.jdk }}

      - name: Execute script
        run: |
          ./${{ inputs.script }} ${{ inputs.args }} 

      - name: Calculate hash for artifact name
        if: ${{ inputs.upload_reports }}
        run: |
          ./.github/scripts/make-hash-for-artifact-name.sh "${{ inputs.args }}"

      - name: Upload reports
        if: ${{ inputs.upload_reports }}
        uses: actions/upload-artifact@v4
        with:
          name: "${{ inputs.artifact_prefix }}-${{ env.HASH }}"
          path: ${{ inputs.report_directory_pattern }}
