name: "Worker"

on:
  workflow_call:
    inputs:
      script:
        required: true
        type: string
        description: "Script to execute"
      args:
        required: false
        type: string
        description: "Arguments for the script"

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Execute script
        run: |
          chmod +x ${{ inputs.script }}
          ./${{ inputs.script }} ${{ inputs.args }} 
